<a href="https://colab.research.google.com/github/GergelyTuri/sleep/blob/master/notebooks/length_of_sleep_sessions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This notebook analyzes the length of sleep sessions
* 6/28/2023 - first version

In [1]:
!git clone https://github.com/GergelyTuri/sleep.git
%cd sleep
!pip install .

Cloning into 'sleep'...
remote: Enumerating objects: 254, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 254 (delta 6), reused 9 (delta 3), pack-reused 242
Receiving objects: 100% (254/254), 1.07 MiB | 1.64 MiB/s, done.
Resolving deltas: 100% (132/132), done.
/content/sleep
Processing /content/sleep
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: sleep
  Building wheel for sleep (setup.py) ... done
  Created wheel for sleep: filename=sleep-0.1-py3-none-any.whl size=997 sha256=0bd3df538ba5e78833e0b7ab5c430664ea65d3673c55524a33f73639f9f1b8c3
  Stored in directory: /tmp/pip-ephem-wheel-cache-m55divhm/wheels/10/eb/42/5281370ac4a2d7b033087761ebaa8f968a9ef5108cbc009a46
Successfully built sleep
Installing collected packages: sleep
Successfully installed sleep-0.1

In [ ]:
%cd '/content/sleep/'
!git pull

/content/sleep
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), 366 bytes | 366.00 KiB/s, done.
From https://github.com/GergelyTuri/sleep
   0a114f3..d95b5d7  master     -> origin/master
Updating 0a114f3..d95b5d7
Fast-forward
 base/eeg.py | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

In [2]:
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
sns.set_context('paper')

from sleep.base import core
from sleep.base import eeg

In [7]:
def time_spent_awake_sleep(df: pd.DataFrame) -> tuple:
  all_frames = data.shape[0]
  awake_frames = len(data[data['awake'] == True])
  awake_interv_lenght = round(awake_frames / all_frames *100, 2)
  sleep_interval_lenght = round(100-awake_interv_lenght,2)
  return (awake_interv_lenght, sleep_interval_lenght)

In [4]:
dr = core.GoogleDrive()
mount = core.GoogleDrive.mount_drive()
data_path = dr.shared_drive_data_path()

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).

In [5]:
mice_db = core.MouseDatabase()
mice = mice_db.load_mouse_database()
mice

,mouseID,day,sessionID,cellType,trialID,eeg_data,significantCells,sima folder,note
1,5HT2afl05b_1,7_7_SD,TSeries-07072021-0833_GC1-001,GC,747,velo_eeg.csv,redo,TSeries-07072021-0833_GC1-001_Cycle00001_Eleme...,
2,5HT2afl05b_1,7_7_SD,TSeries-07072021-0833_GC2-003,GC,745,velo_eeg.csv,redo,TSeries-07072021-0833_GC2-003_Cycle00001_Eleme...,"looks good, uploaded"
3,5HT2afl05b_1,7_7_SD,TSeries-07072021-0833_MC1-002,MC,740,velo_eeg.csv,redo,TSeries-07072021-0833_MC1-002_Cycle00001_Eleme...,
4,5HT2afl05b_1,7_7_SD,TSeries-07072021-0833_MC2-004,MC,749,velo_eeg.csv,redo,TSeries-07072021-0833_MC2-004_Cycle00001_Eleme...,"nice, uploaded"
5,5HT2afl05b_2,7_6_SD,TSeries-07062021-0844_GC-001,GC,762,velo_eeg.csv,redo,TSeries-07062021-0844_GC-001_Cycle00001_Elemen...,uploaded
6,5HT2afl05b_2,7_6_SD,TSeries-07062021-0844_MC-002,MC,761,velo_eeg.csv,redo,TSeries-07062021-0844_MC-002_Cycle00001_Elemen...,uploaded
7,5HT2afl05b_2,7_6_SD,TSeries-07062021-0844_MC2-004,MC,760,velo_eeg.csv,redo,TSeries-07062021-0844_MC2-004_Cycle00001_Eleme...,"best, uploaded"
8,126031_5,11_23,TSeries-11232022-GC-MC-002,GC,876,velo_eeg.csv,redo,TSeries-11232022-GC-MC-002.sima,"very nice 2p, but ca signal craps off after ab..."

In [5]:
mouse = '5HT2afl05b_1'
day = '7_7_SD'
session = 'TSeries-07072021-0833_GC1-001'

In [8]:
result_data = []
for mouse, day, session in zip(mice['mouseID'], mice['day'], mice['sessionID']):
    data = eeg.load_eeg_velocity_data(mouse, day, session)
    times = time_spent_awake_sleep(data)
    result_data.append([mouse, day, session, times[0], times[1]])

result_df = pd.DataFrame(result_data, columns=['mouse', 'day', 'session', 'awake', 'sleep'])
result_df

          mouse     day                        session  awake  sleep
0  5HT2afl05b_1  7_7_SD  TSeries-07072021-0833_GC1-001  91.78   8.22
1  5HT2afl05b_1  7_7_SD  TSeries-07072021-0833_GC2-003  50.00  50.00
2  5HT2afl05b_1  7_7_SD  TSeries-07072021-0833_MC1-002  51.44  48.56
3  5HT2afl05b_1  7_7_SD  TSeries-07072021-0833_MC2-004  20.33  79.67
4  5HT2afl05b_2  7_6_SD   TSeries-07062021-0844_GC-001  52.44  47.56
5  5HT2afl05b_2  7_6_SD   TSeries-07062021-0844_MC-002  38.67  61.33
6  5HT2afl05b_2  7_6_SD  TSeries-07062021-0844_MC2-004  25.44  74.56
7      126031_5   11_23     TSeries-11232022-GC-MC-002  16.13  83.87

In [10]:
result_df[['awake', 'sleep']] = result_df[['awake', 'sleep']].astype('float')

In [13]:
result_df.describe()

           awake      sleep
count   8.000000   8.000000
mean   43.278750  56.721250
std    24.352302  24.352302
min    16.130000   8.220000
25%    24.162500  48.310000
50%    44.335000  55.665000
75%    51.690000  75.837500
max    91.780000  83.870000